INSERT INTO events (
    org_id,
    title,
    description,
    category,
    start_at,
    end_at,
    location,
    capacity,
    ticket_type,
    status,
    created_at,
    updated_at,
    waitlist_enabled,
    waitlist_offer_window,
    waitlist_queue_cap
)
VALUES
  (
    1,
    'Tech Talk',
    'Introductory session on modern software engineering',
    'tech',
    NOW() + INTERVAL '1 day',
    NOW() + INTERVAL '1 day 2 hours',
    'Hall A',
    100,
    'free',
    'published',
    NOW(),
    NOW(),
    TRUE,
    20,
    50
  ),
  (
    1,
    'Art Exhibit',
    'Student art showcase',
    'arts',
    NOW() + INTERVAL '3 days',
    NOW() + INTERVAL '3 days 3 hours',
    'Gallery 1',
    200,
    'free',
    'published',
    NOW(),
    NOW(),
    FALSE,
    NULL,
    NULL
  ),
  (
    1,
    'Business Meetup',
    'Networking event for business students',
    'business',
    NOW() + INTERVAL '5 days',
    NOW() + INTERVAL '5 days 2 hours',
    'Conference Room',
    120,
    'free',
    'submitted',   -- must be submitted, not draft
    NOW(),
    NOW(),
    TRUE,
    15,
    30
  ),
  (
    1,
    'Music Festival',
    'Live student music performances',
    'music',
    NOW() + INTERVAL '2 days',
    NOW() + INTERVAL '2 days 4 hours',
    'Main Stage',
    300,
    'paid',
    'published',
    NOW(),
    NOW(),
    FALSE,
    NULL,
    NULL
  ),
  (
    1,
    'AI Workshop',
    'Hands-on introduction to machine learning',
    'tech',
    NOW() + INTERVAL '7 days',
    NOW() + INTERVAL '7 days 2 hours',
    'Lab B',
    50,
    'free',
    'published',
    NOW(),
    NOW(),
    TRUE,
    30,
    100
  )
ON CONFLICT DO NOTHING;
