BEGIN;

-- Ensure users table has the columns your code expects
ALTER TABLE IF EXISTS users
  ADD COLUMN IF NOT EXISTS password_hash TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS approved BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS student_id TEXT;

-- Make users.id auto-increment (identity) if it isn't already
DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_name='users'
      AND column_name='id'
      AND (identity_generation IS NULL OR identity_generation = '')
  ) THEN
    EXECUTE 'ALTER TABLE users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY';
  END IF;
END$$;

-- Create organizer_requests table used by /auth/request-organizer and admin approvals
CREATE TABLE IF NOT EXISTS organizer_requests (
  id         SERIAL PRIMARY KEY,
  user_id    INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  org_name   TEXT NOT NULL,
  status     TEXT NOT NULL DEFAULT 'pending'
             CHECK (status IN ('pending','approved','rejected')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  reviewed_at TIMESTAMPTZ,
  UNIQUE (user_id, org_name)
);

COMMIT;
